### ISSUE TITLE
Uncertain between the transcript and the wav

### ISSUE THREAD

**Issue by aijianiula0601** [numediart/EmoV-DB#2]
The file of “cmuarctic.data” has two version transcripts like arctic_a0086 and arctic_b0086,but the wav only has the numbers for suffix in wav name like neutral_85-112_0086.wav. It's confuse for me between  the transcript text and wav name.

**Comment by noetits** [comment]
only "arctic_a*" sentences were used

You can look into "EmoV-DB/align_db.py", there is a function called "load_emov_db(path_to_EmoV_DB)" that takes care of mapping the right transcripts to the file paths as well as speaker and emotion category

**Comment by aijianiula0601** [comment]
Thanks. I encounter another problem. The file  of anger_309-336_0322.wav in directory 'not_sort_version/bea/angry'  does not correspond to the transcript text '( arctic_a0322 "This is a common experience with all of us." )' in cmuarctic.data

**Comment by noetits** [comment]
I tried to manually filter out the mismatch in the "sorted version". You can either use the sorted version, with some missing examples, or use the not sorted version if you make the corrections.

**Comment by aijianiula0601** [comment]
OK,Thanks!
