### ISSUE TITLE
Alternative link to sorted EmoV-DB

### ISSUE THREAD

**Issue by Linths** [numediart/EmoV-DB#3]
Hello, first of all thanks for the great corpus!

I wondered, could you provide the sorted EmoV-DB in an alternative way too? I have issues downloading data from the mega.nz website, it keeps failing. Tools like megatools are supposed to help but also fail.

The unsorted dataset provided unfortunately isn't complete (e.g. bea/disgust doesn't exist). Maybe the sorted dataset can be put up on https://coe.northeastern.edu/ as well?

**Comment by Linths** [comment]
Eventually I was able to download from mega.nz using the MEGAsync app. I will leave this issue open because I think for others it still is useful to have a simple link to wget from. Feel free to close the issue though!

**Comment by bagustris** [comment]
Having this issue too, in some countries and companies (like mine) the use of mega is blocked. Better to provide in the official link above.

**Comment by noetits** [comment]
I finally worked on that, it is now available on (see readme): https://openslr.org/115/

Thanks a lot to them!
